version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-demo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
  app:
    image: root938/node-app:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-demo
      DB_USER: root
      DB_PASS: root
      DB_NAME: demo
    depends_on:
      - mysql


